# Generated by Django 4.1.3 on 2022-12-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_users_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BinaryField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.BinaryField(primary_key=True, serialize=False),
        ),
    ]
